expenses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from expenses import views

app_name = 'expenses'

urlpatterns = ([
  path('', views.index, name='index'),
  path('admin/', admin.site.urls),
  path('accounts/', include('django.contrib.auth.urls')),

  path('about/', views.AboutView.as_view(), name='about'),

  path('expenses/', views.EventListView.as_view(), name='event_list'),

  path('event/add/', views.EventCreateView.as_view(), name='event_add'),
  path('event/<int:pk>/', views.EventUpdateView.as_view(), name='event_update'),
  path('event/<int:pk>/delete/', views.EventDeleteView.as_view(), name='event_delete'),
  path('event/<int:pk>/genPDF/', views.event_genPDF, name='event_genPDF'),
  path('event/<int:pk>/uploadAtt/', views.upload_file, name='upload_file'),
  path('event/<int:pk>/delAtt/<int:id>/', views.delete_file, name='delete_file'),
  path('event/<int:pk>/send/', views.event_send, name='event_send'),

  path('event/<int:pk>/travel/', views.travel_list, name='travel_list'),
  path('event/<int:pk>/travel/add/', views.travel_add, name='travel_add'),
  path('event/<int:pk>/travel/<int:id>/', views.travel_update, name='travel_update'),
  path('event/<int:pk>/travel/<int:id>/delete/', views.travel_delete, name='travel_delete'),

  path('event/<int:pk>/days/add/', views.days_add, name='days_add'),
  path('event/<int:pk>/days/', views.days_update, name='days_update'),

  path('referee/settings', views.referee_settings, name='referee_settings'),
  path('referee/<int:pk>/update/', views.referee_update, name='referee_update'),

])
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
               
# if settings.DEBUG:
#   assert isinstance(settings.MEDIA_ROOT, object)
#   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expensesProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    path('', include('expenses.urls')),
]

expenses/models.py
import uuid

from django.db import models
from django import forms
from django.urls import reverse
from django.utils import timezone
from localflavor.generic.models import IBANField
from localflavor.generic.countries.sepa import IBAN_SEPA_COUNTRIES

# import datetime
# ISO_date ="2024-02-17"
# default_date = datetime.date.fromisoformat(ISO_date)

# Create your models here.

class Club(models.Model):
    name = models.CharField(max_length=50)
    street = models.CharField(max_length=50)
    houseno = models.IntegerField()
    pid = models.IntegerField()
    city = models.CharField(max_length=50)
    region = models.CharField(max_length=50, default='Bayern')

    def __str__(self):
        return self.name
        #return '(id: ' + str(self.id) + ') ' + self.name



TYPE_CHOICES = [('KFZ', 'KFZ'), ('Flug', 'Flug'), ('Zug', 'Zug')]

class Travel(models.Model):
    event = models.ForeignKey('expenses.Event', on_delete=models.CASCADE, related_name='events_travel')
    traveldate = models.DateTimeField(null=True)
    starttime = models.TimeField(null=True)
    startlocation = models.CharField(max_length=30, default=" ", blank=False)
    endtime = models.TimeField(null=True)
    duration = models.CharField(max_length=4, default="00:00 ", blank=True)
    endlocation = models.CharField(max_length=30, default=" ", blank=False)
    type = models.CharField(max_length=30, choices=TYPE_CHOICES, default='KFZ')  # PKW, Flugzeug, Bahn
    km = models.IntegerField()
    comment = models.CharField(max_length=30, blank=True)

    class Meta:
        ordering = ['traveldate']

    def get_absolute_url(self):
        return reverse('expenses:travel_list', kwargs={'pk': self.pk})

    def __str__(self):
        return self.endlocation



INT_CHOICES = [(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')]
class Days(models.Model):
    event = models.ForeignKey('expenses.Event', on_delete=models.CASCADE, related_name='events_days')
    iNOfOneDayTravel = models.IntegerField(choices=INT_CHOICES, default=0)
    iNOfMoreDaysTravel = models.IntegerField(choices=INT_CHOICES, default=0)
    iNOfDaysBetween = models.IntegerField(choices=INT_CHOICES, default=0)
    iNOfNights = models.IntegerField(choices=INT_CHOICES, default=0)
    iNOfTravelDays = models.IntegerField(choices=INT_CHOICES, default=0)
    cComment = models.CharField(max_length=100, blank=True)

    def get_absolute_url(self):
        return reverse('expenses:travel_list', kwargs={'pk': self.pk})

    def __str__(self):
        return self.iNOfTravelDays

def generate_filename(instance, filename):
    event = instance.event
    # ext = filename.split('.')[-1]
    # filename = f'{uuid.uuid4()}.{ext}'
    return f"attachments/{event.id}/{filename}"

class UploadedFile(models.Model):
    event = models.ForeignKey('expenses.Event', on_delete=models.CASCADE, related_name='events_uploaded_files')
    # file = models.FileField(upload_to='attachments/')
    file = models.FileField(upload_to=generate_filename)
    file_name = models.CharField(max_length=100, blank=True)
    uploaded_date = models.DateTimeField(auto_now_add=True)
    file_size = models.IntegerField(default=0)



class Event(models.Model):
    referee = models.ForeignKey('auth.User', on_delete=models.DO_NOTHING, related_name='events_referee')
    name = models.CharField(max_length=100)
    startdate = models.DateTimeField(null=True)
    enddate = models.DateTimeField(null=True)
    status = models.BooleanField(default=False)  # sent = True
    game = models.ForeignKey('expenses.Game', on_delete=models.DO_NOTHING, related_name='events_game')
    club = models.ForeignKey('expenses.Club', on_delete=models.DO_NOTHING, related_name='events_club')
    # attachment = models.FileField(upload_to='attachments/%Y/%m/%d', blank=True)
    # attachment = models.FileField(upload_to='attachments/{%event.pk%}', blank=True)
    attachment = models.FileField(upload_to='attachments/', blank=True)

    class Meta:
        ordering = ['-startdate']

    def get_absolute_url(self):
        return reverse('expenses:travel_list', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' ' + str(self.club)


class Game(models.Model):
    name = models.CharField( max_length=50)
    AK = models.CharField(max_length=20)


    def __str__(self):
        return self.name + ' ' + self.AK
        #return '(id: ' + str(self.id) + ') ' + self.name + ' ' + self.AK


class Receipt(models.Model):
    event = models.ForeignKey('expenses.Event', on_delete=models.CASCADE, related_name='events_receipt')
    file = forms.FileField()

    def __str__(self):
        return self.id


class Referee(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    email = models.EmailField(default=' ')
    street = models.CharField(max_length=50)
    houseno = models.CharField(max_length=50)
    pid = models.IntegerField()
    city = models.CharField(max_length=50)
    telefon = models.CharField(max_length=20)
    mobile = models.CharField(max_length=20, default=' ', blank=True)
    IBAN = IBANField(include_countries=IBAN_SEPA_COUNTRIES)
    #IBAN = models.CharField(max_length=22)
    BIC = models.CharField(max_length=12, default='BIC')
    nameBank = models.CharField(max_length=30, default='Bankname')

    def get_absolute_url(self):
        #return reverse('expenses:referee_detail', pk=1)
        #return reverse('referee_detail', kwargs={'pk':self.pk})
        return reverse('referee_detail', args=[str(self.id)])

    def __str__(self):
        #return '(id: ' + str(self.id) + ') ' + self.lastname + ' ' + self.firstname
        return self.firstname + ' ' + self.lastname


class Rates(models.Model):
    kmallowence = models.CharField(max_length=5)           #0.30 Euro
    dailyallowence = models.CharField(max_length=5)        #15 Euro
    fulldayallowence = models.CharField(max_length=5)      #30 Euro
    dailycompensation = models.CharField(max_length=5)     #80 Euro
    bfreduction = models.CharField(max_length=5)           #-6 Euro

    def __str__(self):
        return self.id

expenses/forms.py
import bootstrap_datepicker_plus
from django import forms
from expenses.models import Club, Travel, Event, Game, Receipt, Referee, Rates, Days, UploadedFile
from django.forms import Textarea, RadioSelect, DateInput
from django.core import validators
from django.contrib.auth.models import User
from bootstrap_datepicker_plus.widgets import DatePickerInput, TimePickerInput, DateTimePickerInput
from crispy_forms.helper import FormHelper

# from django.forms import fields
# import datetime
# import time

class TravelForm(forms.ModelForm):
  required_css_class = 'required'

  class Meta:
    model = Travel
    fields = ['traveldate', 'starttime', 'startlocation', 'endtime', 'endlocation', 'type', 'km', 'comment']
    widgets={
      'traveldate': DatePickerInput(),
      'starttime': TimePickerInput(),
      'endtime': TimePickerInput(),
    }
    type = forms.ChoiceField(label="Art", choices=[('K', 'KFZ'), ('F', 'Flug'), ('Z', 'Zug')])
    km = forms.IntegerField(label="Gefahrene km")
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows':5, 'cols':20,}))


class DaysForm(forms.ModelForm):
  required_css_class = 'required'
  class Meta:
    model = Days
    fields = ['iNOfOneDayTravel', 'iNOfMoreDaysTravel', 'iNOfDaysBetween', 'iNOfTravelDays', 'iNOfNights', 'cComment']
    widgets = {
      'cComment': forms.Textarea(attrs={'rows':5, 'cols':20,}),
    }
    rates_list = Rates.objects.all()
    rates = rates_list[0] # nur eine Zeile/Object Setting


class EventForm(forms.ModelForm):
  required_css_class = 'required'

  class Meta:
    model = Event
    fields = ('name', 'game', 'club', 'startdate', 'enddate')
    widgets = {
      'startdate': DatePickerInput(),
      'enddate': DatePickerInput(),
    }
    labels = {'name':'Name', 'game':'Wettspiel', 'club':'Golfclub', 'startdate':'1. Turniertag', 'enddate':'Letzter Turniertag',}

    name = forms.CharField(widget=forms.TextInput(attrs={'cols': 80, 'rows': 10, 'autofocus': True}))


class UploadFileForm(forms.ModelForm):

  class Meta:
    model = UploadedFile
    fields = ('file',)


class RefereeForm(forms.ModelForm):
  required_css_class = 'required'

  firstname = forms.CharField(max_length=30, label='Vorname', widget=forms.Textarea(attrs={'cols':22, 'rows': 1, 'autofocus': True}))
  lastname = forms.CharField(max_length=30, label='Nachname', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))
  email = forms.EmailField(label='E-Mail', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))
  street = forms.CharField(max_length=40, label='Straße', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))
  houseno = forms.CharField(max_length=30, label='Hausnummer', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))
  pid = forms.IntegerField(label='Postleitzahl', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))
  city = forms.CharField(max_length=30, label='Stadt', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))
  telefon = forms.CharField(max_length=30, required=False, label='Telefonnummer', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))
  mobile = forms.CharField(max_length=30, required=False, label='Mobil',
                            widget=forms.Textarea(attrs={'cols': 22, 'rows': 1}))
  IBAN = forms.CharField(min_length=22, max_length=34, label='IBAN', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))
  BIC = forms.CharField(max_length=12, label='BIC', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))
  nameBank = forms.CharField(max_length=30, label='Name der Bank', widget=forms.Textarea(attrs={'cols':22, 'rows': 1}))

  class Meta():
    model = Referee
    exclude = ('author',)


  def clean_IBAN(self):
    data = self.cleaned_data['IBAN']
    if len(data) < 22:
      raise ValueError('Bitte 22 Zeichen eingeben')
    return data

templates/expenses/about.html
{% extends 'base.html' %}

{% block content %}

  <h3>Erläuterungen</h3>
  <br>
  <p>Vielen Dank für die Nutzung von Expenses!
    <br><br>
    <p>Es ermöglicht eine komfortable Erstellung, Änderung und Übermittlung der Reisekostenabrechung an den BGV.</p>
  <br>
  <p>Die Angaben zur Person unter Einstellungen sind Voraussetzung für die Übermittlung.</p>
  <br>
  <p>Eine neue Abrechnung wird mit + erstellt. Austragungsort und Wettspielart sind auszuwählen.</p>
  
  {% comment %}<p>Dazu ist der Abfragemodus mit Call Settings (L/R,r/s) auf</p>
  <ul>
  <li>Links (L)/Rechts (R)</li>
  <li>zufällige Auswahl (r)/der Reihe nach (s)</li>
  </ul>
  <p>für jedes Kapitel separat einstellbar.</p>
  <br>
  <p>Mit Click auf Chapters werden alle Kapitel angezeigt. Die Angaben in Klammern rechts bedeuten:</p>
  <p>(Anzahl aller Textpaare/bereits abgefragte Textpaare/davon nicht richtig beantwortet).</p>
  <br>
  <p>Die Abfrage wird nur innerhalb eine Kapitels gestartet und eingestellt.</p>
  <ul>
  <li>All (x): alle Textpaare werden berücksichtigt</li>
  <li>Called (x): es werden nur die Textpaare abgefragt, die noch nicht abgefragt wurden.</li>
  <li>Failed (x): es werden nur die Textpaare abgefragt, die falsch beantwortet wurden.</li>
  <li>Reset: alle Textpaare werden auf "noch nicht abgefragt" gestellt; damit ist Called und All gleich der Anzahl der Textpaare und Failed=0</li>
  </ul>
  <p>Wenn die Zahl bei All und Called gleich ist und Failed (0), startet keine Anfrage.</p>
  <p>Der Status der Textpaare (gewusst oder nicht) wird mit Häkchen und Minuszeichen innerhalb der Kapitelansicht dargestellt.</p>

 <p>Innerhalb der Abfrage wird bei click auf Check gleich das nächste Textpaar abgefragt, falls die Antwort richtig war.</p>
 <p>Sonst wird die Antwort und der richtige Text untereinandergestellt. Der User entscheidet dann, ob die Antwort richtig oder falsch ist.</p>
 <p>"Leere Eingaben" sind nicht zulässig.</p>

 <p>Die Abfrage und das Erstellen von Textpaaren wird mit Cancel beendet.</p>
{% endcomment %}

  <table>
    {% for item in object_list %}
      <tr>
        <td> {{ item.expenses.author }}</td>
        <td> {{ item.referee.lastname }}</td>
        
      </tr>
    {% endfor %}
  </table>

{% endblock content %}

templates/expenses/event_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Abrechnung löschen{% endblock title %}

{% block content %}
  
  <div class="container">
    <form method="post" class="card">
		{% csrf_token %}
		<h4>Abrechnung:</h4>
		<p>"{{event}}" löschen?</p>
      
    <div style="margin-left: 400px">
      <a style="margin-right: 40px;" class="btn btn-secondary" href="{% url 'expenses:event_list' %}">Cancel</a>
      <button type="submit" class="btn btn-danger">Löschen</button>
    </div>
      
{#		<p class="form-buttons">#}
{#			<input type="submit" class="btn btn-danger" value="Löschen">#}
{#			<a href="{% url 'expenses:event_list' %}" class="btn btn-secondary">Cancel</a>#}
{#		</p>#}
	</form>
  
   
{#    {% if event_list.count > 0 %}#}
{#      {% for event in event_list %}#}
{#        <table border="0">#}
{#          <tr>#}
{#            <td width="75%"><h6><a class="event-link" href="{% url 'expenses:event_detail' pk=event.pk %}">{{ event.name }}: {{ event.club }}</a> </h6></td>#}
    {#        <td width="15%"><h5>({{ chap.pairs.count }}/{{ chap.sum1 }}/{{ chap.sum2 }})</h5></td>#}
{#    #}
{#            <td width="5%" align="right"><a  href="{% url 'expenses:event_update' pk=event.pk %}"><i aria-hidden class="fa fa-pencil"></i></a></td>#}
{#            <td width="15%" align="right"><a  href="{% url 'expenses:event_delete' pk=event.pk %}"><i aria-hidden class="fa fa-trash-o" ></i></a></td>#}
{#    #}
{#          </tr>#}
{#    #}
{#        </table>#}
{#      {% endfor %}#}
{#    {% else %}#}
{#      <p>Noch keine Abrechnungen erstellt!</p>#}
{#    {% endif %}#}
  
  </div>

{% endblock content %}

templates/expenses/referee_detail.html
{% extends 'base.html' %}

{% block title %}{{ user.username }}{% endblock title %}

{% block content %}

  {% if user.is_authenticated %}
    <br><br>
    <h6>Abgespeicherte Einstellungen für {{ user.first_name }}  {{ user.last_name }}:</h6>

    <br>

    <table>
      <tr><td class="label_l">Vorname: </td><td class="label_r">{{ referee.firstname }}</td></tr>
      <tr><td class="label">Nachname: </td><td>{{ referee.lastname }}</td></tr>
      <tr><td class="label">Straße: </td><td>{{ referee.street }}</td></tr>
      <tr><td class="label">E-Mail: </td><td>{{ referee.email }}</td></tr>
      <tr><td class="label">Hausnummer: </td><td>{{ referee.houseno }}</td></tr>
      <tr><td class="label">Postleitzahl: </td><td>{{ referee.pid }}</td></tr>
      <tr><td class="label">Stadt: </td><td>{{ referee.city }}</td></tr>
      <tr><td class="label">Telefonnummer: </td><td>{{ referee.telefon }}</td></tr>
      <tr><td class="label">Mobil: </td><td>{{ referee.mobile }}</td></tr>
      <tr><td class="label">IBAN: </td><td>{{ referee.IBAN }}</td></tr>
      <tr><td class="label">BIC: </td><td>{{ referee.BIC }}</td></tr>
      <tr><td class="label">Bankname: </td><td>{{ referee.nameBank }}</td></tr>

    </table>
    
    <table style="margin-top: 30px">
      <tr>
        <td><a style="margin-left: 0px;" class="btn btn-secondary" href="{% url 'expenses:event_list' %}">Cancel</a></td>
        <td><a style="margin-left: 150px;" class="btn btn-info" href="{% url 'expenses:referee_update' pk=referee.pk %}">Ändern</a></td>
      </tr>
    </table>

  {% endif %}
{% endblock content %}

templates/expenses/travel_list.html
{% extends 'base.html' %}

{% block title %}Reiseabrechnung{% endblock title %}

{% block content %}
{#{% if event.referee.id %}#}
{#    <div class="container">#}
{#      <table class="table-referee">#}
{#        <tr>#}
{#          <td class="td-bold">Adresse:</td>#}
{#        <td>{{ referee.firstname }} {{ referee.lastname }}</td>#}
{#        <td>{{ referee.street }}</td>#}
{#        <td>{{ referee.pid }} {{ referee.city }}</td>#}
{#        <td style="text-align: right">{{ referee.email }}</td>#}
{#        </tr>#}
{#        #}
{#        <tr>#}
{#          <td class="td-bold">Telefon:</td>#}
{#        <td>{{ referee.telefon }} </td>#}
{#        <td class="td-bold">Mobil:</td>#}
{#        <td>{{ referee.mobile }}</td>#}
{#        <td></td>#}
{#        </tr>#}
{#        #}
{#        <tr>#}
{#          <td class="td-bold">Bank:</td>#}
{#        <td>{{ referee.IBAN }}</td>#}
{#        <td>{{ referee.BIC }}</td>#}
{#        <td>{{ referee.nameBank }}</td>#}
{#        <td></td>#}
{#        </tr>#}
{#      </table>#}
{#    </div>#}
{#    <hr style="height:3px;">#}
{#{% endif %}  #}

<div class="container">

  <div class="row">
    <div class="col-10 td-bold">
      Reise: {{ event.game }} im {{ event.club }} am {{ event.startdate|date:"d.m.y" }}
    </div>
    <div class="col-2" style="text-align: right">
      Fahrt hinzufügen <a href="{% url 'expenses:travel_add' pk=event.pk %}">{% include 'plus-square.svg' %} </a>
    </div>
  </div>
</div>
      
{% if travel_list.count > 0 %}
  <br>
  <div class="container text-left">

      <div class="row text-left td-bold">
        <div class="col-1">Abfahrt</div>
        <div class="col-1"></div>
        <div class="col-2"></div>
        <div class="col-1">Ankunft</div>
        <div class="col-2"></div>
        <div class="col-1"></div>
        <div class="col-1">km</div>
        <div class="col-1">Std. je Tag</div>
        <div class="col-1">Kommentar</div>
        <div class="col-1"></div>
        <div class="col-1"></div>
      </div>

  </div>
{#  <br>#}
  <div class="container text-left">

    {% for travel in travel_list %}
      <div class="row">
        <div class="col-1">{{ travel.traveldate|date:"d.m.y" }}</div>
        <div class="col-1">{{ travel.starttime|time:"H:i" }}</div>
        <div class="col-2">{{ travel.startlocation }}</div>
        <div class="col-1">{{ travel.endtime|time:"H:i" }}</div>
        <div class="col-2">{{ travel.endlocation }}</div>
        <div class="col-1">{{ travel.type }}</div>
        <div class="col-1">{{ travel.km }}</div>
        <div class="col-1">{{ travel.duration }}</div>
        <div class="col-1">{{ travel.comment }}</div>
        <div class="col text-right"><a  href="{% url 'expenses:travel_update' pk=event.pk id=travel.id %}"><i aria-hidden="true" class="fa fa-pencil"></i></a></div>
        <div class="col text-right"><a  href="{% url 'expenses:travel_delete' pk=event.pk id=travel.id %}"><i aria-hidden="true" class="fa fa-trash-o" ></i></a></div>
      </div>
    {% endfor %}

  </div>
  <br>
  <hr style="height:1px;">
  
  <div class="container text-left">
    <div class="row">
      <div class="col-4">Gefahrene km</div>
      <div class="col-1">{{ gefkm }} km</div>
      <div class="col-4 td-bold">Kilometergeld</div>
      <div class="col-2" style="text-align: right">{{ Kilometergeld }} €</div>
    </div>
  </div>
        
  {% if icount > 0 %}
    <br>
    <div class="container text-left">
      <div class="row">
        <div class="col-10 td-bold">Tagegeldberechnung</div>
        <div class="col-2" style="text-align: right">
            Tage ändern <a href="{% url 'expenses:days_update' pk=event.pk %}"><i aria-hidden="true" class="fa fa-pencil"></i></a>
        </div>
      </div>
      <br>
      {% for days in  days_list %}
        <div class="row">
          <div class="col-4">Anzahl eintägiger Reisen</div>
          <div class="col-1">{{ days.iNOfOneDayTravel }}</div>
          <div class="col-4">Tagegeld eintägig (8 Std. und mehr)</div>
          <div class="col-2" style="text-align: right" id="Tagegeld">{{ Tagegeld }} €</div>
        </div>
        <div class="row">
          <div class="col-4">An-/Abreisetage (bei Übernachtung)</div>
          <div class="col-1">{{ days.iNOfMoreDaysTravel }}</div>
          <div class="col-4">Tagegeld An-/Abreisetag</div>
          <div class="col-2" style="text-align: right" id="AnAbTagegeld">{{ AnAbTagegeld }} €</div>
        </div>
        <div class="row">
          <div class="col-4">Zwischentage bei mehrtägiger Reise</div>
          <div class="col-1">{{ days.iNOfDaysBetween }}</div>
          <div class="col-4">Tagegeld Zwischentag</div>
          <div class="col-2" style="text-align: right" id="ZwTagegeld">{{ ZwTagegeld }} €</div>
        </div>
        <br>
        <div class="row">
          <div class="col-4">Anzahl Reisetage (Aufwandsentschädigung)</div>
          <div class="col-1">{{ days.iNOfTravelDays }}</div>
          <div class="col-4">Aufwandsentschädigung</div>
          <div class="col-2" style="text-align: right" id="Aufwand">{{ Aufwand }} €</div>
        </div>
        <br>
        <div class="row">
          <div class="col-4">Anzahl der Übernachtungen</div>
          <div class="col-1">{{ days.iNOfNights }}</div>
          <div class="col-4">Abzug wg. Frühstück</div>
          <div class="col-2" style="text-align: right" id="Breakfast">{{ Breakfast }} €</div>
        </div>
        <hr style="height: 1px;">
        
        <div class="row">
          {% if days.cComment %}
            <div class="col-4 td-bold">Anmerkungen Ihrerseits zur Reisekostenabrechnung:</div>
          {% else %}
            <div class="col-4"></div>
          {% endif %}
          <div class="col-1"></div>
          <div class="col-4 td-bold">Tagegeld</div>
          <div class="col-2" style="text-align: right" id="CostAll">{{ CostAll }} €</div>
        </div>
        <div class="row">
          <div class="col-4">{{ days.cComment }}</div>
        </div>
        <br>
        <div class="row">
        <div class="col-5"></div>
        <div class="col-4 td-bold">Erstattungsbetrag (gesamt)</div>
          <div class="col-2" style="font-weight: bold; text-align: right">{{ Erstattungsbetrag }} €</div>
        </div>
        <br>
        
        <div class="row">
          <div class="col-4">
            <a href="{% url 'expenses:upload_file' pk=event.pk %}">Dateien anhängen</a>
          </div>
          <div class="col-1"></div>
          <div class="col-4">
            <a href="{% url 'expenses:event_genPDF' pk=event.pk %}">Reiseabrechnung ansehen </a>
          </div>
        </div>
        
        <br>
        {% if file_list.count > 0 %}
          <div class="row">
            <div class="col-4">Bereits angehängte Dateien:</div>
          </div>
          {%  for files in file_list %}
            <div class="row">
              <div class="col-4"><a href="{{ MEDIA_URL }}{{ files.file }}">{{ files.file_name }}</a></div>
              <div class="col-1">
                <a href="{% url 'expenses:delete_file' pk=event.pk id=files.id %}"><i aria-hidden="true" class="fa fa-trash-o" ></i></a>
              </div>
            </div>
          {% endfor %}
        {% endif %}
        <br>
        
        <div class="row">
          <div class="col-4">
            <a href="{% url 'expenses:event_send' pk=event.pk %}">Abrechnung übermitteln</a>
          </div>
{#          <div class="col-5"></div>#}
{#          <div class="col-4"></div>#}
        </div>
        
        
      {% endfor %}
 
  {% else %} 
    <div class="col-12" style="text-align: right">
      Tage hinzufügen <a href="{% url 'expenses:days_add' pk=event.pk %}">{% include 'plus-square.svg' %} </a>
    </div>
 {% endif %}
  
{% endif %}
<br><br>  

{% endblock content %}