expenses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from expenses import views

app_name = 'expenses'

urlpatterns = ([
  path('', views.index, name='index'),
  path('admin/', admin.site.urls),
  path('accounts/', include('django.contrib.auth.urls')),

  path('about/', views.AboutView.as_view(), name='about'),

  path('expenses/', views.EventListView.as_view(), name='event_list'),

  path('event/add/', views.EventCreateView.as_view(), name='event_add'),
  path('event/<int:pk>/', views.EventUpdateView.as_view(), name='event_update'),
  path('event/<int:pk>/delete/', views.EventDeleteView.as_view(), name='event_delete'),
  path('event/<int:pk>/genPDF/', views.event_genPDF, name='event_genPDF'),
  path('event/<int:pk>/uploadAtt/', views.upload_file, name='upload_file'),
  path('event/<int:pk>/delAtt/<int:id>/', views.delete_file, name='delete_file'),
  path('event/<int:pk>/send/', views.event_send, name='event_send'),

  path('event/<int:pk>/travel/', views.travel_list, name='travel_list'),
  path('event/<int:pk>/travel/add/', views.travel_add, name='travel_add'),
  path('event/<int:pk>/travel/<int:id>/', views.travel_update, name='travel_update'),
  path('event/<int:pk>/travel/<int:id>/delete/', views.travel_delete, name='travel_delete'),

  path('event/<int:pk>/days/add/', views.days_add, name='days_add'),
  path('event/<int:pk>/days/', views.days_update, name='days_update'),

  path('referee/settings', views.referee_settings, name='referee_settings'),
  path('referee/<int:pk>/update/', views.referee_update, name='referee_update'),

])
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
               
# if settings.DEBUG:
#   assert isinstance(settings.MEDIA_ROOT, object)
#   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expensesProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    path('', include('expenses.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="de">

{% load static %}
{#{{ form.media }}#}

<head>
  <meta charset="UTF-8">
  <title>

    {% block title %}
      {{ page_title|default:"Reisekostenabrechnung" }}
    {% endblock title %}
  </title>

 

{#  all I need #}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.de.min.js'></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>


  {# jquery #}
<script src="{% static "admin/js/vendor/jquery/jquery.min.js" %}"></script>

 {% block styles %}{{ form.media }}{% endblock styles %}

  {#fontawesome#}
  {#  <script src="https://kit.fontawesome.com/e58ba3ceba.js" crossorigin="anonymous"></script>#}
{#  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}">#}
{#  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">#}
  {#  <script src="https://use.fontawesome.com/ffda900719.js"></script>#}

  {# Custom CSS#}{#  <link rel="stylesheet" href="{% static '/css/chapters.css' %}">#}
  <link rel="stylesheet" href="{% static 'expenses.css' %}">
  <script src="{% static "main.js" %}"></script>

  {# Fonts#}
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

{#  <script>#}
{#    window.dbdpOptions = {#}
{#    widgetParent: jQuery("#myWidgetParent"),#}
{#    }#}
{#    window.dbdpEvents = {#}
{#        "dp.show": e => console.log("Calendar opened"),#}
{#    } #}
{#  </script>#}

</head>


<body>
  <script src="{% static "main.js" %}"></script>
  
  <!-- NAVBAR -->
  <div class="container">
    <p></p>
    <h4>Bayerischer Golfverband e.V.</h4>
    <h6>Geschäftsstelle: Georg-Brauchle-Ring 93, 80992 München</h6>


    <div class="row nav">

      {% if user.is_authenticated %}

        <li class="nav-item nav-brand col-sm-2">
          <a class="nav-link active" href="{% url 'expenses:event_list' %}"><h4>Abrechnungen</h4></a>
        </li>

        <li class="nav-item col-sm-2">
          <a class="nav-link" href="{% url 'expenses:event_add' %}">{% include 'plus-square.svg' %} </a>
        </li>

        <li class="nav-item col-sm-1">
          <a class="nav-link" href="{% url 'expenses:about' %}">About</a>
        </li>


        <li class="nav-item col-sm-3">
{#          <a class="nav-link" href="{% url 'expenses:referee/{{user.id}}' %}"><span class="far fa-cog"></span></a>#}
          <a class="nav-link" href="{% url 'expenses:referee_settings' %}">Einstellungen</a>
{#          <a class="nav-link" href="{% url 'expenses:referee_new' %}"><i class="far fa-cog"></i>Einstellungen</a>#}
        </li>

        <li class="nav-item col-sm-2">
          <form id="logout-form" action="{% url 'logout' %}" method="post">
            {% csrf_token %}
{#            <button class="btn btn-light" type="submit">Log out</button>#}
            <button type="submit">Log out</button>
          </form>
        </li>
       
        <li class="nav-item col-sm-2">
          <a class="nav-link" href="#">Willkommen: {{ user.first_name}} {{ user.last_name}}</a>
        </li>

      {% else %}

        <li class="nav-item nav-brand col-sm-3">
          <a class="nav-link active" href="#"><h5>Reisekostenabrechnung</h5></a>
        </li>
        <li class="nav-item col-sm-1">
          <a class="nav-link" href="{% url 'expenses:about' %}">About</a>
        </li>

        <li class="nav-item col-sm-3">
          <a class="nav-link" href="https://bayerischer-golfverband.de/home">BGV</a>
        </li>

        <li class="nav-item col-sm-3">
          <a class="nav-link" href="{% url 'login' %}"><span class="fa fa-user-o" aria-hidden="true"></span></a>
        </li>

      {% endif %}

    </div>
  
    <div>
      {% if user.is_authenticated %}
        <div class="container">
          <table class="table-referee">
            <tr>
              <td class="td-bold">Adresse:</td>
              <td>{{ referee.firstname }} {{ referee.lastname }}</td>
              <td>{{ referee.street }}</td>
              <td>{{ referee.pid }} {{ referee.city }}</td>
              <td style="text-align: right">{{ referee.email }}</td>
              </tr>
              
              <tr>
                <td class="td-bold">Telefon:</td>
              <td>{{ referee.telefon }} </td>
              <td class="td-bold">Mobil:</td>
              <td>{{ referee.mobile }}</td>
              <td></td>
              </tr>
              
              <tr>
                <td class="td-bold">Bank:</td>
              <td>{{ referee.IBAN }}</td>
              <td>{{ referee.BIC }}</td>
              <td>{{ referee.nameBank }}</td>
              <td></td>
              </tr>
            </table>
            <hr style="height:3px;">
        </div>
      {% else %}
        <div class="container">
        <p>Bitte einloggen!</p>
        </div>
      {% endif %}
    </div>
  
  

  </div>
  
  
  
  {%  include 'expenses/messages.html' %}
  
  <!-- CONTENT BLOCK -->
  <div class="container">

    {% block content %}

    {% endblock content%}

  </div>


</body>
</html>